//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSenseMobile.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgroSenseMobile.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs: {0}.
        /// </summary>
        public static string ActuatorLogsTitle {
            get {
                return ResourceManager.GetString("ActuatorLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuator Name *.
        /// </summary>
        public static string ActuatorNameLabel {
            get {
                return ResourceManager.GetString("ActuatorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Main Pump.
        /// </summary>
        public static string ActuatorNamePlaceholder {
            get {
                return ResourceManager.GetString("ActuatorNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuators.
        /// </summary>
        public static string ActuatorsSectionTitle {
            get {
                return ResourceManager.GetString("ActuatorsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type *.
        /// </summary>
        public static string ActuatorTypeLabel {
            get {
                return ResourceManager.GetString("ActuatorTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device type....
        /// </summary>
        public static string ActuatorTypePlaceholder {
            get {
                return ResourceManager.GetString("ActuatorTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add.
        /// </summary>
        public static string AddReadingButton {
            get {
                return ResourceManager.GetString("AddReadingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area:.
        /// </summary>
        public static string AreaLabel {
            get {
                return ResourceManager.GetString("AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m².
        /// </summary>
        public static string AreaUnit {
            get {
                return ResourceManager.GetString("AreaUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power / Capacity (optional).
        /// </summary>
        public static string CapacityLabel {
            get {
                return ResourceManager.GetString("CapacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 1500 (Watts) or 50 (ml/s).
        /// </summary>
        public static string CapacityPlaceholder {
            get {
                return ResourceManager.GetString("CapacityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity:.
        /// </summary>
        public static string CapacityPrefix {
            get {
                return ResourceManager.GetString("CapacityPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanelTitle {
            get {
                return ResourceManager.GetString("ControlPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT DEVICE STATUS:.
        /// </summary>
        public static string CurrentDeviceStatus {
            get {
                return ResourceManager.GetString("CurrentDeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete actuator &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteActuatorConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteActuatorConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the greenhouse &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteGreenhouseConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteGreenhouseConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sensor &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteSensorConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteSensorConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Actuator.
        /// </summary>
        public static string EditActuatorTitle {
            get {
                return ResourceManager.GetString("EditActuatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sensor.
        /// </summary>
        public static string EditSensorTitle {
            get {
                return ResourceManager.GetString("EditSensorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any greenhouses yet..
        /// </summary>
        public static string EmptyGreenhouses {
            get {
                return ResourceManager.GetString("EmptyGreenhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of device toggles will appear here..
        /// </summary>
        public static string EmptyLogsDesc {
            get {
                return ResourceManager.GetString("EmptyLogsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs are empty.
        /// </summary>
        public static string EmptyLogsTitle {
            get {
                return ResourceManager.GetString("EmptyLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all caught up!.
        /// </summary>
        public static string EmptyNotificationsDesc {
            get {
                return ResourceManager.GetString("EmptyNotificationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notifications.
        /// </summary>
        public static string EmptyNotificationsTitle {
            get {
                return ResourceManager.GetString("EmptyNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records.
        /// </summary>
        public static string EmptyReadingsTitle {
            get {
                return ResourceManager.GetString("EmptyReadingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new value....
        /// </summary>
        public static string EnterNewValuePlaceholder {
            get {
                return ResourceManager.GetString("EnterNewValuePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete: {0}.
        /// </summary>
        public static string ErrorDeleteFailedMessage {
            get {
                return ResourceManager.GetString("ErrorDeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete greenhouse. Check your connection..
        /// </summary>
        public static string ErrorDeleteGreenhouse {
            get {
                return ResourceManager.GetString("ErrorDeleteGreenhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email and password..
        /// </summary>
        public static string ErrorEmptyFields {
            get {
                return ResourceManager.GetString("ErrorEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the name and type..
        /// </summary>
        public static string ErrorFillNameAndType {
            get {
                return ResourceManager.GetString("ErrorFillNameAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string ErrorInvalidNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load devices..
        /// </summary>
        public static string ErrorLoadDevices {
            get {
                return ResourceManager.GetString("ErrorLoadDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load greenhouses..
        /// </summary>
        public static string ErrorLoadGreenhouses {
            get {
                return ResourceManager.GetString("ErrorLoadGreenhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load logs. Check your connection..
        /// </summary>
        public static string ErrorLoadLogs {
            get {
                return ResourceManager.GetString("ErrorLoadLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load notifications. Check your connection..
        /// </summary>
        public static string ErrorLoadNotifications {
            get {
                return ResourceManager.GetString("ErrorLoadNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load readings history..
        /// </summary>
        public static string ErrorLoadReadings {
            get {
                return ResourceManager.GetString("ErrorLoadReadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string ErrorLoginFailed {
            get {
                return ResourceManager.GetString("ErrorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error: {0}.
        /// </summary>
        public static string ErrorSaveFailed {
            get {
                return ResourceManager.GetString("ErrorSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save reading..
        /// </summary>
        public static string ErrorSaveReading {
            get {
                return ResourceManager.GetString("ErrorSaveReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change device state on the server. Reverted to previous state..
        /// </summary>
        public static string ErrorSyncActuator {
            get {
                return ResourceManager.GetString("ErrorSyncActuator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle the device. Check your connection to the server..
        /// </summary>
        public static string ErrorToggleActuator {
            get {
                return ResourceManager.GetString("ErrorToggleActuator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenhouse:.
        /// </summary>
        public static string GreenhouseLabel {
            get {
                return ResourceManager.GetString("GreenhouseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Greenhouses.
        /// </summary>
        public static string GreenhousesPageTitle {
            get {
                return ResourceManager.GetString("GreenhousesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageSection {
            get {
                return ResourceManager.GetString("LanguageSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string LanguageUkrainian {
            get {
                return ResourceManager.GetString("LanguageUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back!.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: {0}.
        /// </summary>
        public static string LogReasonFormat {
            get {
                return ResourceManager.GetString("LogReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Value: {0}).
        /// </summary>
        public static string LogValueFormat {
            get {
                return ResourceManager.GetString("LogValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as read.
        /// </summary>
        public static string MarkAllAsReadTooltip {
            get {
                return ResourceManager.GetString("MarkAllAsReadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Actuator.
        /// </summary>
        public static string NewActuatorTitle {
            get {
                return ResourceManager.GetString("NewActuatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sensor.
        /// </summary>
        public static string NewSensorTitle {
            get {
                return ResourceManager.GetString("NewSensorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileSection {
            get {
                return ResourceManager.GetString("ProfileSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string RegisterHeader {
            get {
                return ResourceManager.GetString("RegisterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Register.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Name *.
        /// </summary>
        public static string SensorNameLabel {
            get {
                return ResourceManager.GetString("SensorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Temp Sensor 1.
        /// </summary>
        public static string SensorNamePlaceholder {
            get {
                return ResourceManager.GetString("SensorNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readings: {0}.
        /// </summary>
        public static string SensorReadingsTitle {
            get {
                return ResourceManager.GetString("SensorReadingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorsSectionTitle {
            get {
                return ResourceManager.GetString("SensorsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Type *.
        /// </summary>
        public static string SensorTypeLabel {
            get {
                return ResourceManager.GetString("SensorTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sensor type....
        /// </summary>
        public static string SensorTypePlaceholder {
            get {
                return ResourceManager.GetString("SensorTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string StateOff {
            get {
                return ResourceManager.GetString("StateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string StateOn {
            get {
                return ResourceManager.GetString("StateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization Error.
        /// </summary>
        public static string SyncErrorTitle {
            get {
                return ResourceManager.GetString("SyncErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TooltipDelete {
            get {
                return ResourceManager.GetString("TooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TooltipEdit {
            get {
                return ResourceManager.GetString("TooltipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Log.
        /// </summary>
        public static string TooltipLogs {
            get {
                return ResourceManager.GetString("TooltipLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readings History.
        /// </summary>
        public static string TooltipReadings {
            get {
                return ResourceManager.GetString("TooltipReadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypePrefix {
            get {
                return ResourceManager.GetString("TypePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Unit (optional).
        /// </summary>
        public static string UnitLabel {
            get {
                return ResourceManager.GetString("UnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. °C, %, ppm.
        /// </summary>
        public static string UnitPlaceholder {
            get {
                return ResourceManager.GetString("UnitPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        public static string UnitPrefix {
            get {
                return ResourceManager.GetString("UnitPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.
        /// </summary>
        public static string UnnamedDevice {
            get {
                return ResourceManager.GetString("UnnamedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCodePlaceholder {
            get {
                return ResourceManager.GetString("VerificationCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerifyButton {
            get {
                return ResourceManager.GetString("VerifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code..
        /// </summary>
        public static string VerifyError {
            get {
                return ResourceManager.GetString("VerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the verification code sent to your email..
        /// </summary>
        public static string VerifyInstruction {
            get {
                return ResourceManager.GetString("VerifyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully verified! You can now log in..
        /// </summary>
        public static string VerifySuccess {
            get {
                return ResourceManager.GetString("VerifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        public static string VerifyTitle {
            get {
                return ResourceManager.GetString("VerifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Greenhouse!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
